-- Создание таблицы chat_room
CREATE TABLE public.chat_room (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255),
    type_chat character varying(255),
    CONSTRAINT chat_room_type_chat_check CHECK (((type_chat)::text = ANY ((ARRAY['USER_CHAT'::character varying, 'TASK_CHAT'::character varying, 'GROUP_CHAT'::character varying])::text[]))),
    CONSTRAINT chat_room_pkey PRIMARY KEY (id)
);

-- Создание таблицы chat_room_users
CREATE TABLE public.chat_room_users (
    chat_rooms_id bigint NOT NULL,
    users_id bigint NOT NULL
);

-- Создание таблицы message
CREATE TABLE public.message (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date timestamp(6) without time zone,
    message character varying(255),
    sender_name character varying(255),
    chat_room_id bigint,
    status character varying(255),
    CONSTRAINT message_pkey PRIMARY KEY (id)
);

-- Создание таблицы event_publication
CREATE TABLE public.event_publication (
    id uuid NOT NULL,
    completion_date timestamp(6) with time zone,
    event_type character varying(255),
    listener_id character varying(255),
    publication_date timestamp(6) with time zone,
    serialized_event character varying(255),
    CONSTRAINT event_publication_pkey PRIMARY KEY (id)
);

-- Создание таблицы status
CREATE TABLE public.status (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255),
    CONSTRAINT status_pkey PRIMARY KEY (id)
);

-- Создание таблицы task
CREATE TABLE public.task (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    title character varying(255),
    status_id bigint,
    profit double precision,
    owner_id bigint,
    CONSTRAINT task_pkey PRIMARY KEY (id)
);

-- Создание таблицы user_crm
CREATE TABLE public.user_crm (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT user_crm_pkey PRIMARY KEY (id),
    CONSTRAINT user_crm_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_ADMIN'::character varying])::text[]))),
    CONSTRAINT ukcklrm5w65cm7rcnwggsvrptnj UNIQUE (username),
    CONSTRAINT ukq4ubbe24j2slho28icks3h0ih UNIQUE (email)
);

-- Внешние ключи
ALTER TABLE ONLY public.task
    ADD CONSTRAINT fk9amdidv53i0hvjvnxkrup18t4 FOREIGN KEY (status_id) REFERENCES public.status(id);

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fkf876lpeagqgrcjrewr4hwjd5q FOREIGN KEY (chat_room_id) REFERENCES public.chat_room(id);

ALTER TABLE ONLY public.chat_room_users
    ADD CONSTRAINT fklkdd3ym1q6bqvshwdavx480m4 FOREIGN KEY (users_id) REFERENCES public.user_crm(id);

ALTER TABLE ONLY public.chat_room_users
    ADD CONSTRAINT fkr3h4upxlajle1awd9o7immaob FOREIGN KEY (chat_rooms_id) REFERENCES public.chat_room(id);